name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      next-version:
        description: 'Override next development version (e.g. 5.0.0-SNAPSHOT). If not set then the version will be calculated by maven release plugin'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    name: Prepare release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_PAT }}"
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Prepare release
        run: |
          if [ -n "${{ github.event.inputs.next-version }}" ]; then
              EXTRA_ARGS=-DdevelopmentVersion=${{ github.event.inputs.next-version }}
          fi
          git config user.name "devopsHazelcast"
          git config user.email "<devops@hazelcast.com>"
          ./mvnw --batch-mode release:prepare release:clean -Darguments="-DskipTests" $EXTRA_ARGS
      - name: Push changes
        run: |
          git push
          git push --tags
